In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
dataset=pd.read_csv("/home/abbas/NAVTTEC/Dataset_files/csvfiles/Data.csv")
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [12]:
salary_col=dataset.iloc[:,2]

In [15]:
salary_mean=salary_col.mean()

In [16]:
salary_mean

63777.77777777778

In [17]:
dataset.iloc[4,2]=salary_mean

In [18]:

dataset

Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes
5   France  35.0  58000.000000       Yes
6    Spain   NaN  52000.000000        No
7   France  48.0  79000.000000       Yes
8  Germany  50.0  83000.000000        No
9   France  37.0  67000.000000       Yes

In [19]:
age_col=dataset.iloc[:,1]

In [20]:
age_col_mean=age_col.mean()

In [21]:
dataset.iloc[6,1]=age_col_mean

In [22]:
dataset

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [23]:
x=dataset.iloc[:,1:-1]
y=dataset.iloc[:,-1]

In [24]:
x

Age        Salary
0  44.000000  72000.000000
1  27.000000  48000.000000
2  30.000000  54000.000000
3  38.000000  61000.000000
4  40.000000  63777.777778
5  35.000000  58000.000000
6  38.777778  52000.000000
7  48.000000  79000.000000
8  50.000000  83000.000000
9  37.000000  67000.000000

In [25]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [26]:
#Label encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(y)

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [27]:
y=le.fit_transform(y)

In [28]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [29]:
#Spliting dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)

In [30]:
x_train

Age   Salary
9  37.000000  67000.0
1  27.000000  48000.0
6  38.777778  52000.0
7  48.000000  79000.0
3  38.000000  61000.0
0  44.000000  72000.0
5  35.000000  58000.0

In [31]:
x_test

Age        Salary
2  30.0  54000.000000
8  50.0  83000.000000
4  40.0  63777.777778

In [32]:
y_train

array([1, 1, 0, 1, 0, 0, 1])

In [33]:
y_test

array([0, 0, 1])

In [34]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [35]:
x_train

array([[-0.2029809 ,  0.44897083],
       [-1.82168936, -1.41706417],
       [ 0.08478949, -1.0242147 ],
       [ 1.5775984 ,  1.62751925],
       [-0.04111006, -0.14030338],
       [ 0.93011502,  0.94003267],
       [-0.52672259, -0.43494049]])

In [36]:
x_test

array([[-1.22474487, -1.07298811],
       [ 1.22474487,  1.33431759],
       [ 0.        , -0.26132948]])

In [37]:
#Training
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [38]:
#Prediction
print(knn.predict([[28,50000]]))

[1]


In [39]:
y_pred=knn.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))


[[1 0]
 [1 0]
 [0 1]]


In [40]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[0 2]
 [1 0]]


0.0