In [1]:
import numpy as np

In [2]:
#creating an 1D array
arr=np.array([1,4,6])
arr

array([1, 4, 6])

In [3]:
#creating 2D array
arry=np.array([[5,7,9],[2,6,8]])
arry

array([[5, 7, 9],
       [2, 6, 8]])

In [4]:
#indexing an array
arr[1]

4

In [5]:
#size of array
arr.size

3

In [7]:
#shape of array
arry.shape


(2, 3)

In [8]:
#data type of array
arr.dtype

dtype('int32')

In [9]:
#number of dimension of array
arr.ndim

1

In [10]:
#eye function:prints 1 on the diagonal
ar=np.eye(4)
ar


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
#diagonal function: prints the given numbers on diagonal
dg=np.diag([2,4,12])
dg

array([[ 2,  0,  0],
       [ 0,  4,  0],
       [ 0,  0, 12]])

In [12]:
#random function:
#rand function: prints random float numbers between 0 and 1
rn=np.random.rand(5)
rn

array([0.63225849, 0.70371477, 0.64030811, 0.65530781, 0.25660728])

In [14]:
#randint function: prints random integers
rd=np.random.randint(0,50,10)
rd

array([45, 10, 25, 31, 31, 43, 23, 28, 30,  5])

In [15]:
#randin function: prints both +ive and -ive
rm=np.random.randn(10)
np.argmax(rm,axis)

array([-1.5691598 ,  1.09136036, -0.24150094, -1.26469675,  1.42519445,
       -1.33132734, -0.80666309,  0.27500054, -0.66006343,  0.21402229])

In [16]:
#ones function prints 1 in all values in array
one=np.ones((2,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#zero function prints 0 in all the values of array
zero=np.zeros((1,2))
zero

array([[0., 0.]])

# mathematical operations


In [18]:
a=np.array([200,300,500])
a

array([200, 300, 500])

In [19]:
a*2

array([ 400,  600, 1000])

In [23]:
b=([100,200,800])

In [24]:
a-b

array([ 100,  100, -300])

In [25]:
#comparison opearator
c = a > b
c

array([ True,  True, False])