In [1]:
import numpy as np

In [5]:
#arange 
ran=np.arange(1,20,2)
ran

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [3]:
#linespace: prints an array with equal differences 
ls=np.linspace(0,1000,100)
ls

array([   0.        ,   10.1010101 ,   20.2020202 ,   30.3030303 ,
         40.4040404 ,   50.50505051,   60.60606061,   70.70707071,
         80.80808081,   90.90909091,  101.01010101,  111.11111111,
        121.21212121,  131.31313131,  141.41414141,  151.51515152,
        161.61616162,  171.71717172,  181.81818182,  191.91919192,
        202.02020202,  212.12121212,  222.22222222,  232.32323232,
        242.42424242,  252.52525253,  262.62626263,  272.72727273,
        282.82828283,  292.92929293,  303.03030303,  313.13131313,
        323.23232323,  333.33333333,  343.43434343,  353.53535354,
        363.63636364,  373.73737374,  383.83838384,  393.93939394,
        404.04040404,  414.14141414,  424.24242424,  434.34343434,
        444.44444444,  454.54545455,  464.64646465,  474.74747475,
        484.84848485,  494.94949495,  505.05050505,  515.15151515,
        525.25252525,  535.35353535,  545.45454545,  555.55555556,
        565.65656566,  575.75757576,  585.85858586,  595.95959

In [5]:
# reshape

rs=np.arange(1,10).reshape(3,3)
rs

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# ravel: it changes the array into 1D and a copy is made if needed original is not changed

rv=np.ravel(rs)
rv

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Transpose of a matrix

rs.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
# Vertical Stack 

a=([[1,2,3],[4,5,6]])
b=([[2,3,4],[5,6,7]])

np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [5, 6, 7]])

In [17]:
# Horizontal stack
np.hstack((a,b))

array([[1, 2, 3, 2, 3, 4],
       [4, 5, 6, 5, 6, 7]])