In [3]:
import pandas as pd
import numpy as np

In [16]:
a=[1,2,3,0,np.NaN]
b=pd.Series(a)
b

0    1.0
1    2.0
2    3.0
3    0.0
4    NaN
dtype: float64

In [8]:

print(b.index)

RangeIndex(start=0, stop=3, step=1)


In [18]:
# shows how many values are null or missing
pd.isnull(b)

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [20]:

b.notnull()

0     True
1     True
2     True
3     True
4    False
dtype: bool

In [22]:
# giving series a name
b.name="Population"
b

0    1.0
1    2.0
2    3.0
3    0.0
4    NaN
Name: Population, dtype: float64

In [24]:
# giving name to index of series
b.index.name="Integers"
b

Integers
0    1.0
1    2.0
2    3.0
3    0.0
4    NaN
Name: Population, dtype: float64

In [41]:
# columns sequence change, 
# index number change,
# indexing
# value replace by indexing, arange , and new series
# creating new column and also by condition
# deleting column
# index slicing
# Index Function
# is condition
# in condition
# reindexing series
# forward fill
# reshape (data frame)
# reindex dataframe
# column reindexing
# drop function Series , dataframe (axis)
# inplace function
# selection
# indexing (dataframe)
#

# Series

In [4]:
obj=pd.Series([4,7,-8,5])
obj

0    4
1    7
2   -8
3    5
dtype: int64

In [6]:
# accessing values
obj.values

array([ 4,  7, -8,  5], dtype=int64)

In [8]:
#accessing indexes
obj.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
# changing indexes
obj2=pd.Series([4,7,-5,3] , index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [17]:
# selecting single value or set of values
obj2['b']
obj2[['d','a']]

d    4
a   -5
dtype: int64

In [19]:
# using operations like scalar multiplication,math functions,boolean array
obj2*3

d    12
b    21
a   -15
c     9
dtype: int64

In [21]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [23]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [25]:
'c' in obj2

True

In [26]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3=pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [30]:
# index of list
states=['Ohio','Texas','Oregon','California']
obj4=pd.Series(sdata,index=states)
obj4

Ohio          35000.0
Texas         71000.0
Oregon        16000.0
California        NaN
dtype: float64

In [31]:
# isnull function shows how many values are null
pd.isnull(obj4)

Ohio          False
Texas         False
Oregon        False
California     True
dtype: bool

In [32]:
# notnull function shows how many values are not null
pd.notnull(obj4)

Ohio           True
Texas          True
Oregon         True
California    False
dtype: bool

In [33]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [34]:
obj4

Ohio          35000.0
Texas         71000.0
Oregon        16000.0
California        NaN
dtype: float64

In [35]:
# allignment
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [36]:
# naming the series 
obj4.name='Population'
obj4

Ohio          35000.0
Texas         71000.0
Oregon        16000.0
California        NaN
Name: Population, dtype: float64

In [38]:
# naming index
obj4.index.name='State'
obj4

State
Ohio          35000.0
Texas         71000.0
Oregon        16000.0
California        NaN
Name: Population, dtype: float64

In [40]:
# A series index altered by inplace assignment
obj.index=['qari','khizar','furqan','nomi']
obj

qari      4
khizar    7
furqan   -8
nomi      5
dtype: int64

# Data Frame

In [2]:
# Creating Data frame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} 
frame=pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [3]:
# Head function: (head function by default prints the first five values of the data frame)
frame.head(4)

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4

In [4]:
# Adding a column that is not in the dictionary;;;(It will be null values in the new column)
frame2=pd.DataFrame(data, columns=['year','state','pop','debt'], index=['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [5]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [6]:
# printing a specific columns
frame2['pop']

one      1.5
two      1.7
three    3.6
four     2.4
five     2.9
six      3.2
Name: pop, dtype: float64

In [7]:
#
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [8]:
frame2['debt']=10.2
frame2

year   state  pop  debt
one    2000    Ohio  1.5  10.2
two    2001    Ohio  1.7  10.2
three  2002    Ohio  3.6  10.2
four   2001  Nevada  2.4  10.2
five   2002  Nevada  2.9  10.2
six    2003  Nevada  3.2  10.2

In [10]:
frame2['debt']=np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [11]:
val=pd.Series([-1.2,-1.5,-1.7], index=['two','four','five'])
frame2['debt']=val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [12]:
frame2['eastern']=frame2.state== 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [13]:
# deleting a column
del frame2['eastern']

In [14]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [15]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}} 
frame3=pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [16]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [17]:
pdata = {'Ohio': frame3['Ohio'][:-1],'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [18]:
frame3.index.name='year';frame3.columns.name='state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [19]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [21]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

# Index Objects

In [26]:
obj=pd.Series(range(3),index=['a','b','c'])
index=obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [28]:
index[1:]

Index(['b', 'c'], dtype='object')

In [5]:
label=pd.Index(np.arange(3))
label

Int64Index([0, 1, 2], dtype='int64')

In [10]:
obj2=pd.Series([-1.2,-1.3,0],index=label)
obj2

0   -1.2
1   -1.3
2    0.0
dtype: float64

In [12]:
obj2.index is label

True

In [14]:
# pandas labels can contain duplicate labels 
dup_labels=pd.Index(['a','a','b','b'])
dup_labels

Index(['a', 'a', 'b', 'b'], dtype='object')

In [16]:
p=pd.Series([1,2,3,4],index=dup_labels)
p

a    1
a    2
b    3
b    4
dtype: int64

# Reindexing

In [18]:
obj3=pd.Series([9,13,52,145],index=['d','b','c','a'])
obj3

a      9
b     13
c     52
d    145
dtype: int64

In [20]:
# reindexing Series
obj4=obj3.reindex(['a','b','c','d','e'])
obj4

a      9.0
b     13.0
c     52.0
d    145.0
e      NaN
dtype: float64

In [21]:
obj5=pd.Series(['Green','White','Red'],index=[0,2,4])
obj5

0    Green
2    White
4      Red
dtype: object

In [22]:
# Forward Fill Method: It forward fills the missing value

obj6=obj5.reindex(range(6), method='ffill')
obj6

0    Green
1    Green
2    White
3    White
4      Red
5      Red
dtype: object

In [23]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [24]:
# Reindexing DataFrame can alter row or column or both, when passed one sequence,in result it reindexes row
frame2=frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [29]:
# columns can be reindexed by passing columns keyword
states=['Texas','Peshawar','California']
frame2.reindex(columns=states)

Texas  Peshawar  California
a    1.0       NaN         2.0
b    NaN       NaN         NaN
c    4.0       NaN         5.0
d    7.0       NaN         8.0

# Droping Entries from an axis

In [4]:
# Droping Entries from series

obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [6]:
# Droping an entry

new_obj=obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [8]:
# Droping multiple entries

obj.drop(['c','d'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [9]:
# Droping entries from Data frame

data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [11]:
# Calling Drop in dataframe with sequence of label will drop entries from rows

data.drop('Ohio')

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [12]:
# We can drop values from columns by passing axis=1 or axis='columns'

data.drop(['one','three'],axis=1)

two  four
Ohio        1     3
Colorado    5     7
Utah        9    11
New York   13    15

In [13]:
# Inplace function: It modify the size or shape of a Series or DataFrame without returning a new object

obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64