In [2]:
#Importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#Importing dataset

data=pd.read_csv('E:\csv files\Salary_Data.csv')
data

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [16]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [17]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [18]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [19]:
#Splitting the data into training set and test set

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.41,random_state=2)

In [20]:
# Training the simple linear regression model on training set

from sklearn.linear_model import LinearRegression
regress = LinearRegression()
regress.fit(x_train,y_train)

LinearRegression()

In [30]:
# Testing the model
y_pred=regress.predict(x_test)

In [29]:
y_pred.round(1)

array([ 35650.7,  33724.6,  66468.2,  58763.8,  91507.3,  80913.8,
       102100.8,  52022.5,  42392. ,  88618.2,  51059.4, 115583.5,
        61652.9])

In [31]:
y_test

array([ 46205.,  39343.,  61111.,  57189.,  98273.,  93940., 113812.,
        60150.,  43525.,  91738.,  56642., 112635.,  56957.])

In [37]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[ 35650.68566474  46205.        ]
 [ 33724.59398199  39343.        ]
 [ 66468.15258871  61111.        ]
 [ 58763.78585772  57189.        ]
 [ 91507.34446444  98273.        ]
 [ 80913.84020932  93940.        ]
 [102100.84871955 113812.        ]
 [ 52022.4649681   60150.        ]
 [ 42392.00655436  43525.        ]
 [ 88618.20694032  91738.        ]
 [ 51059.41912672  56642.        ]
 [115583.49049879 112635.        ]
 [ 61652.92338184  56957.        ]]


In [40]:
# Checking accuracy
regress.score(x_testt,y_test)

0.9211439168978532

In [43]:
# Mean Squared error 

from sklearn.metrics import mean_squared_error
print("Mean Sqr Err:" ,mean_squared_error(y_test,y_pred))

Mean Sqr Err: 51209936.9286912
