# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Importing Dataset

In [2]:
data=pd.read_csv('E:\csv files/titanic.csv')
data

PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2              3                             Heikkinen, Miss. Laina       3   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4              5                           Allen, Mr. William Henry       3   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas       2   
887          888                       Graham, Miss. Margaret Edith       1   
888          889           Johnston, Miss. Catherine Helen "Carrie"       3   
889          890                              Behr, Mr. Karl Howell       1   
890          891                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    female  38.0      1      0          PC 17599  71.2833   C85        C   
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    female  35.0      1      0            113803  53.1000  C123        S   
4      male  35.0      0      0            373450   8.0500   NaN        S   
..      ...   ...    ...    ...               ...      ...   ...      ...   
886    male  27.0      0      0            211536  13.0000   NaN        S   
887  female  19.0      0      0            112053  30.0000   B42        S   
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S   
889    male  26.0      0      0            111369  30.0000  C148        C   
890    male  32.0      0      0            370376   7.7500   NaN        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 12 columns]

# Droppping Columns

In [3]:
df1=data.drop(['PassengerId',"Name",'SibSp','Parch','Ticket','Cabin','Embarked'] , axis=1)

In [4]:
df1

Pclass     Sex   Age     Fare  Survived
0         3    male  22.0   7.2500         0
1         1  female  38.0  71.2833         1
2         3  female  26.0   7.9250         1
3         1  female  35.0  53.1000         1
4         3    male  35.0   8.0500         0
..      ...     ...   ...      ...       ...
886       2    male  27.0  13.0000         0
887       1  female  19.0  30.0000         1
888       3  female   NaN  23.4500         0
889       1    male  26.0  30.0000         1
890       3    male  32.0   7.7500         0

[891 rows x 5 columns]

# Filling Null values

In [5]:
mean_age=df1['Age'].mean()

In [6]:
mean_age

29.69911764705882

In [7]:
df1['Age'].fillna(mean_age,inplace=True)

In [8]:
df1

Pclass     Sex        Age     Fare  Survived
0         3    male  22.000000   7.2500         0
1         1  female  38.000000  71.2833         1
2         3  female  26.000000   7.9250         1
3         1  female  35.000000  53.1000         1
4         3    male  35.000000   8.0500         0
..      ...     ...        ...      ...       ...
886       2    male  27.000000  13.0000         0
887       1  female  19.000000  30.0000         1
888       3  female  29.699118  23.4500         0
889       1    male  26.000000  30.0000         1
890       3    male  32.000000   7.7500         0

[891 rows x 5 columns]

In [9]:
x=df1.iloc[:,:-1]
y=df1.iloc[:,-1]

# One Hot Encoding

In [20]:
# OnehotEncoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# encoder to encode type is OneHotEncoding and which index or column
ct=ColumnTransformer([('encoder',OneHotEncoder(),[1])],remainder="passthrough")
x=np.array(ct.fit_transform(x))

In [11]:
x

array([[ 0.        ,  1.        ,  3.        , 22.        ,  7.25      ],
       [ 1.        ,  0.        ,  1.        , 38.        , 71.2833    ],
       [ 1.        ,  0.        ,  3.        , 26.        ,  7.925     ],
       ...,
       [ 1.        ,  0.        ,  3.        , 29.69911765, 23.45      ],
       [ 0.        ,  1.        ,  1.        , 26.        , 30.        ],
       [ 0.        ,  1.        ,  3.        , 32.        ,  7.75      ]])

In [12]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

# Splitting the dataset

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=0)

# Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [15]:
x_train

array([[-0.72592065,  0.72592065, -1.5325562 ,  1.62393675, -0.12253019],
       [ 1.37756104, -1.37756104, -1.5325562 ,  1.47020331,  0.91812372],
       [-0.72592065,  0.72592065,  0.84844757, -2.21939923,  0.29950338],
       ...,
       [-0.72592065,  0.72592065,  0.84844757, -0.0133922 , -0.51276504],
       [ 1.37756104, -1.37756104,  0.84844757,  0.47093596, -0.31228976],
       [-0.72592065,  0.72592065, -0.34205431,  2.31573723,  0.13566725]])

In [16]:
x_test

array([[-0.76537495,  0.76537495,  0.77963055,  0.03127218, -0.324475  ],
       [-0.76537495,  0.76537495,  0.77963055,  0.03127218, -0.45513843],
       [-0.76537495,  0.76537495,  0.77963055, -1.72139852, -0.04706937],
       ...,
       [-0.76537495,  0.76537495,  0.77963055, -0.17713524, -0.32455255],
       [ 1.30654916, -1.30654916,  0.77963055, -0.87205371, -0.45616356],
       [-0.76537495,  0.76537495, -1.64991582,  0.03127218, -0.07362838]])

# Training The Decision Tree Classifier Model

In [17]:
from sklearn.tree import DecisionTreeClassifier
cls=DecisionTreeClassifier()
cls.fit(x_train,y_train)

DecisionTreeClassifier()

# Predicting a new result (Decision Tree Classifier)

In [22]:
print(cls.predict([[2,1,0,22,30]]))

[0]


# Test Set Results (Decision Tree Classifier)

In [23]:
y_pred=cls.predict(x_test)
y_pred

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0], dtype=int64)

# Confusion Matrix (Decision Tree Classifier)

In [24]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test , y_pred)
print(cm)
accuracy_score(y_test , y_pred)

[[152  16]
 [ 31  69]]


0.8246268656716418

# Training The Naive Bayes Model

In [25]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)

GaussianNB()

# Predicting a new result (Naive Bayes)

In [27]:
print(cls.predict(sc.transform([[2,1,0,22,30]])))

[1]


# Test Set Results (Naive Bayes)

In [28]:
ypred=nb.predict(x_test)
y_pred

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0], dtype=int64)

# Confusion Matrix (Naive Bayes)

In [29]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test , ypred)
print(cm)
accuracy_score(y_test , ypred)

[[137  31]
 [ 28  72]]


0.7798507462686567