In [1]:
import numpy as np

In [3]:
# task 1

a=np.array([[[1,3,5],[2,4,6],[7,8,9]]])
a

array([[[1, 3, 5],
        [2, 4, 6],
        [7, 8, 9]]])

In [9]:
# task 2

b=np.random.randint(0,50,9)
b
b.reshape(3,3)

array([[44, 10, 44],
       [30, 16, 44],
       [ 5, 48, 32]])

In [17]:
# task 3

c=np.arange(10,21)
print(c)
c.size

[10 11 12 13 14 15 16 17 18 19 20]


11

In [20]:
# task 4

d=np.ones((10))*5
d

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [23]:
# task 5

e=np.arange(1,10)
print(e)
e.reshape(3,3)

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# task 6

f=np.arange(1,11)
f[f%2==0]=0
f

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [34]:
# task 7

g=np.random.rand(9).reshape(3,3)
g

array([[0.07770365, 0.86527964, 0.21116419],
       [0.22233037, 0.47608152, 0.9970104 ],
       [0.43022405, 0.0174089 , 0.21566213]])

In [7]:
# task 8

h=np.arange(1,17).reshape(4,4)
print(h)
print("-----------")
n=h[1:4,1:3]
print(n)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-----------
[[ 6  7]
 [10 11]
 [14 15]]


In [2]:
# task 9

i=([[1,2,3],[4,5,6]])
j=([[7,8,9],[10,11,12]])
print("Vertical Stack")
k=np.vstack((i,j))
print(k)
print("Horizontal Stack")
l=np.hstack((i,j))
print(l)

Vertical Stack
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontal Stack
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [43]:
# task 10

m=np.diag([5,4,3])
m

array([[5, 0, 0],
       [0, 4, 0],
       [0, 0, 3]])