# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Importing Dataset

In [2]:
data=pd.read_csv('E:\csv files\Data.csv')
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
data.iloc[4,-2]=63777
data.iloc[6,1]=39
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63777.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  39.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
x=data.iloc[:,1:-1]
y=data.iloc[:,-1]

In [5]:
x

Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0  63777.0
5  35.0  58000.0
6  39.0  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

In [6]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

# Label Encoding

In [7]:
from sklearn.preprocessing import LabelEncoder
y1=LabelEncoder()
y1.fit_transform(y)

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [8]:
y=y1.fit_transform(y)

In [9]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Splitting Data into Training set and Test Set

In [32]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.2, random_state=0)

# Feature Scaling

In [33]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [20]:
x_train

array([[-0.16347432, -1.07811699],
       [-0.01816381, -0.07018988],
       [ 0.56307822,  0.63357038],
       [-0.30878483, -0.30785767],
       [-1.90720041, -1.42045447],
       [ 1.14432024,  1.23266096],
       [ 1.43494126,  1.57499844],
       [-0.74471635, -0.56461078]])

In [21]:
x_test

array([[-1., -1.],
       [ 1.,  1.]])

# Training the KNN Model on Training Set

In [34]:
from sklearn.neighbors import KNeighborsClassifier
cls = KNeighborsClassifier(n_neighbors=5)
cls.fit(x_train,y_train)

KNeighborsClassifier()

# Predicting a new result

In [35]:
print(cls.predict(sc.transform([[28,50000]])))

[1]


# Predicting the test set result

In [36]:
y_pred=cls.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 0]]


# Making Confusion Matrix

In [37]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test , y_pred)
print(cm)
accuracy_score(y_test , y_pred)

[[0 2]
 [0 0]]


0.0