In [1]:
import tensorflow as tf


In [2]:
tf.__version__

'2.6.0'

In [3]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [8]:
a=tf.constant(10)

In [5]:
print(a)

tf.Tensor(10, shape=(), dtype=int32)


In [9]:
b=tf.constant(10.2)#create float constnt
b

<tf.Tensor: shape=(), dtype=float32, numpy=10.2>

In [14]:
#create string constant
c=tf.constant("NCBC UET")
c

<tf.Tensor: shape=(), dtype=string, numpy=b'NCBC UET'>

In [15]:
#create bool constant
d=tf.constant(True)
d

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [16]:
#create constant numpy array/list/tuple
#we use numpy for numerical calculationn
import numpy as np
np_array=tf.constant(np.array([1,2,3,3]))
np_array

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 3])>

In [18]:
#create 2d array
td2=tf.constant([[1,2],[2,3],[3,4]])
td2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]], dtype=int32)>

In [20]:
#create 1-d constannt
t2d_1=tf.constant([1,2,3,4,5,6],shape=(3,2),dtype='int32')
t2d_1


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [21]:
#cretate n-d constant
t3d=tf.constant([[[1,2],[2,3],[3,4]]],dtype='int32')
t3d

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3],
        [3, 4]]], dtype=int32)>

In [22]:
#type of constant
type(t3d)

tensorflow.python.framework.ops.EagerTensor

In [24]:
#shape of constant
t3d.shape

TensorShape([1, 3, 2])

In [25]:
#access constant value
td2.shape

TensorShape([3, 2])