In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
a = tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
a.numpy()

array([1, 2, 3, 4], dtype=int32)

In [ ]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [ ]:
t_f = tf.Variable([1.1,2.2,3.3,4.4])
t_f

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.1, 2.2, 3.3, 4.4], dtype=float32)>

In [ ]:
t_s = tf.Variable(['a','b','c','d'])
t_s

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'a', b'b', b'c', b'd'], dtype=object)>

In [ ]:
t_b = tf.Variable([True,False])
t_b

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [ ]:
t_cx = tf.Variable([3+4j])
t_cx

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+4.j])>

In [ ]:
t_con = tf.constant([1,2,3,4])
t_con
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
t_2d = tf.Variable([[2,3],[4,5]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
t_2d_2 = tf.Variable([[2,3],[4,5]])
t_2d_2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
tf.reshape(a,shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.argmax(t_2d_2)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [ ]:
tf.argmax(t_2d_2).numpy()

array([1, 1])

In [ ]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.convert_to_tensor(t_2d_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:

a.assign_sub([1,1,1,1])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [ ]:
a.assign_add([2,2,2,2])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>