# Tensor Flow

In [1]:
import tensorflow as tf


In [2]:
tf.__version__

'2.6.1'

In [3]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [4]:
a=tf.constant(10)

In [5]:
print(a)

tf.Tensor(10, shape=(), dtype=int32)


In [6]:
b=tf.constant(10.2)#create float constnt
b

<tf.Tensor: shape=(), dtype=float32, numpy=10.2>

In [7]:
#create string constant
c=tf.constant("NCBC UET")
c

<tf.Tensor: shape=(), dtype=string, numpy=b'NCBC UET'>

In [8]:
#create bool constant
d=tf.constant(True)
d

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [9]:
#create constant numpy array/list/tuple
#we use numpy for numerical calculationn
import numpy as np
np_array=tf.constant(np.array([1,2,3,3]))
np_array

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 3])>

In [10]:
#create 2d array
td2=tf.constant([[1,2],[2,3],[3,4]])
td2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [3, 4]])>

In [11]:
#create 1-d constannt
t2d_1=tf.constant([1,2,3,4,5,6],shape=(3,2),dtype='int32')
t2d_1


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [12]:
#cretate n-d constant
t3d=tf.constant([[[1,2],[2,3],[3,4]]],dtype='int32')
t3d

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3],
        [3, 4]]])>

In [13]:
#type of constant
type(t3d)

tensorflow.python.framework.ops.EagerTensor

In [14]:
#shape of constant
t3d.shape

TensorShape([1, 3, 2])

In [15]:
#access constant value
td2.shape

TensorShape([3, 2])

# TensorFlow Variables

In [16]:
a = tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [17]:
a.numpy()

array([1, 2, 3, 4])

In [18]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [19]:
t_f = tf.Variable([1.1,2.2,3.3,4.4])
t_f

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.1, 2.2, 3.3, 4.4], dtype=float32)>

In [20]:
t_s = tf.Variable(['a','b','c','d'])
t_s

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'a', b'b', b'c', b'd'], dtype=object)>

In [21]:
t_b = tf.Variable([True,False])
t_b

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [22]:
t_cx = tf.Variable([3+4j])
t_cx

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+4.j])>

In [23]:
t_con = tf.constant([1,2,3,4])
t_con
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [24]:
t_2d = tf.Variable([[2,3],[4,5]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [25]:
t_2d_2 = tf.Variable([[2,3],[4,5]])
t_2d_2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [26]:
tf.reshape(a,shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [27]:
tf.argmax(t_2d_2)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1], dtype=int64)>

In [28]:
tf.argmax(t_2d_2).numpy()

array([1, 1], dtype=int64)

In [29]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [30]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [31]:
tf.convert_to_tensor(t_2d_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [32]:
a.assign_sub([1,1,1,1])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([0, 1, 2, 3])>

In [33]:
a.assign_add([2,2,2,2])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([2, 3, 4, 5])>

# TensorFlow Placeholder

In [34]:
tf.compat.v1.disable_eager_execution()

In [35]:
a = tf.compat.v1.placeholder(dtype=tf.float32, shape=(400,400))
a

<tf.Tensor 'Placeholder:0' shape=(400, 400) dtype=float32>

In [36]:
a.dtype

tf.float32

In [37]:
a.shape

TensorShape([400, 400])

In [38]:
a.name

'Placeholder:0'

In [39]:
b = tf.compat.v1.placeholder(dtype=tf.float32, shape = (400,400))
b

<tf.Tensor 'Placeholder_1:0' shape=(400, 400) dtype=float32>

In [40]:
c = tf.add(a,b)
c

<tf.Tensor 'Add:0' shape=(400, 400) dtype=float32>

In [41]:
import numpy as np
ones_array = np.ones((400,400), np.float32)
ones_array

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [42]:
with tf.compat.v1.Session() as sess:
  d = sess.run(c, feed_dict = {a:ones_array,b:ones_array*2})
d

array([[3., 3., 3., ..., 3., 3., 3.],
       [3., 3., 3., ..., 3., 3., 3.],
       [3., 3., 3., ..., 3., 3., 3.],
       ...,
       [3., 3., 3., ..., 3., 3., 3.],
       [3., 3., 3., ..., 3., 3., 3.],
       [3., 3., 3., ..., 3., 3., 3.]], dtype=float32)