In [1]:
import numpy as np
import pandas as pd



In [2]:
# Load data
data=pd.read_csv(r'D:\AI and DL Course\MachineLearningCourse\csvfiles\\HR_comma_sep.csv')

data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [12]:
# Import LabelEncoder
from sklearn.preprocessing import LabelEncoder

# Creating labelEncoder
le =LabelEncoder()

# Converting string labels into numbers.
data['salary']=le.fit_transform(data['salary'])
data['sales ']=le.fit_transform(data['sales'])

In [13]:
dataset=data.drop('left',axis='columns')

In [14]:
dataset.head()
left=data.left

In [6]:
dataset=pd.concat([dataset,left],axis='columns')
dataset.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  promotion_last_5years  sales  salary  \
0                   3              0                      0  sales       1   
1                   6              0                      0  sales       2   
2                   4              0                      0  sales       2   
3                   5              0                      0  sales       1   
4                   3              0                      0  sales       1   

   sales   left  
0       7     1  
1       7     1  
2       7     1  
3       7     1  
4       7     1

In [15]:
dataset=dataset.drop('sales',axis='columns')

In [16]:
dataset.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  promotion_last_5years  salary  sales   \
0                   3              0                      0       1       7   
1                   6              0                      0       2       7   
2                   4              0                      0       2       7   
3                   5              0                      0       1       7   
4                   3              0                      0       1       7   

   sales_enc   
0           7  
1           7  
2           7  
3           7  
4           7

In [17]:
# Spliting data into Feature and
#X=data[['satisfaction_level', 'last_evaluation', 'number_project', 'average_montly_hours', 'time_spend_company', 'Work_accident', 'promotion_last_5years', 'sales ', 'salary']]
#y=data['left']

X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)  # 70% training and 30% test

In [29]:
# Import MLPClassifer 
from sklearn.neural_network import MLPClassifier

# Create model object
clf = MLPClassifier(hidden_layer_sizes=(7,5),
                    random_state=7,
                    verbose=True,
                    learning_rate_init=0.01)

# Fit data onto the model
clf.fit(X_train,y_train)

Iteration 1, loss = 6.90918511
Iteration 2, loss = 2.15414132
Iteration 3, loss = 2.10590869
Iteration 4, loss = 2.09205923
Iteration 5, loss = 2.05215255
Iteration 6, loss = 2.02961262
Iteration 7, loss = 1.99408831
Iteration 8, loss = 1.97456292
Iteration 9, loss = 1.91849519
Iteration 10, loss = 1.85098936
Iteration 11, loss = 1.77045050
Iteration 12, loss = 1.69458421
Iteration 13, loss = 1.61406081
Iteration 14, loss = 1.53471636
Iteration 15, loss = 1.46095445
Iteration 16, loss = 1.40015214
Iteration 17, loss = 1.33898878
Iteration 18, loss = 1.30118095
Iteration 19, loss = 1.22413549
Iteration 20, loss = 1.17645563
Iteration 21, loss = 1.15265163
Iteration 22, loss = 1.09213759
Iteration 23, loss = 1.05569270
Iteration 24, loss = 1.02473567
Iteration 25, loss = 0.99291737
Iteration 26, loss = 0.96860890
Iteration 27, loss = 0.94798228
Iteration 28, loss = 0.92197414
Iteration 29, loss = 0.90261463
Iteration 30, loss = 0.87421134
Iteration 31, loss = 0.87418987
Iteration 32, los

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(7, 5), learning_rate='constant',
              learning_rate_init=0.01, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=7, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=True, warm_start=False)

In [31]:
# Make prediction on test dataset
y_pred=clf.predict(X_test)

# Import accuracy score 
from sklearn.metrics import accuracy_score

# Calcuate accuracy
accuracy_score(y_test,y_pred)

0.9991111111111111

In [ ]:
#y_pred = clf.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 371    0    0    0    0    0    0    0    0    0]
 [   0  243    0    0    0    0    0    0    0    0]
 [   0    0  228    0    0    0    0    0    0    0]
 [   0    0    0  245    0    0    0    0    0    0]
 [   0    0    0    0  152    0    0    0    0    0]
 [   0    0    0    0    0  281    0    0    0    0]
 [   0    0    0    0    0    0  240    0    0    0]
 [   0    0    0    0    0    0    0 1207    0    0]
 [   0    0    0    0    0    0    0    0  689    4]
 [   0    0    0    0    0    0    0    0    0  840]]


0.9991111111111111