# NumPy

In [ ]:
# it stands for numerical python
#DEF: in python numpy is a package which contains classes, variables, large library of mathematical funtion etc to work with scientific etc to worl with scientific calculations.
#numpy is used to create n-dimentional arrays.
#pip list
#pip install numpy

In [1]:
import numpy as np

In [36]:
arry=np.array([2.0,4,6])
arry

array([2., 4., 6.])

In [37]:
arry.dtype

dtype('float64')

In [35]:
arry.size

3

In [38]:
arry.shape

(3,)

In [3]:
arry[2]

6

In [5]:
#
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
#
aee=np.diag([4,6,8])
aee

array([[4, 0, 0],
       [0, 6, 0],
       [0, 0, 8]])

In [18]:
#between 0 and 1
ae=np.random.rand(10)
ae

array([0.15101889, 0.63343097, 0.59974448, 0.04270312, 0.12358951,
       0.52284559, 0.72294165, 0.50286602, 0.96984914, 0.53934168])

In [24]:
#Generate a 1-D array containing random integers from 0 to 100
ae=np.random.randint(1,100,10)
ae

array([97, 19, 89,  1,  4, 88, 69, 10,  6, 37])

In [28]:
#both +ive and -ive
ae=np.random.randn(5)
ae

array([ 1.10613193,  0.86928492, -0.62414594, -1.18254395,  0.3274417 ])

# Mathematical Operations:

In [39]:
a=np.array([100,200,300])
a+5

array([105, 205, 305])

In [43]:
b=np.array([1000,200,9300])
a*b

array([ 100000,   40000, 2790000])

# Comparison operator:

In [44]:
c = a==b
c

array([False,  True, False])

In [48]:
#print values from 0 to 100 and divide it into 10 equal parts
aer=np.linspace(1,100,10)
aer

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

# 2D Arrays

In [52]:
ae=np.array([[1,2,3],[4,5,6]])
ae

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
ae.ndim

In [49]:
ar=np.ones((5,4))
ar

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
ar=np.ones(2)
ar

array([1., 1.])

In [4]:
ar=np.ones((2))
ar

array([1., 1.])

In [6]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])