# Numpy Attributes

In [1]:
import numpy as np

In [21]:
#1 array

In [ ]:
#2 arange

In [4]:
#3 linespace
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [2]:
#4 Reshape
c=np.arange(1,10).reshape(3,3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#5 ravel converts it into 1D array and copy is made if needed orginal is not changed
b=np.ravel(c)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
#6 transpose
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
a=np.array([[2,3,4],[4,6,7]])
print(a)

[[2 3 4]
 [4 6 7]]


In [11]:
b=np.array([[9,4,1],[2,0,7]])
print(b)

[[9 4 1]
 [2 0 7]]


In [12]:
#7
m=np.vstack((a,b))
m

array([[2, 3, 4],
       [4, 6, 7],
       [9, 4, 1],
       [2, 0, 7]])

In [13]:
#8
np.hstack((a,b))

array([[2, 3, 4, 9, 4, 1],
       [4, 6, 7, 2, 0, 7]])

In [ ]:
[2, 3, 4],
[4, 6, 7],
[9, 8, 7],

In [14]:
#9 
np.argmin(a)

0

In [15]:
#10
np.argmax(a)

5

In [16]:
#11 argsort()
a.argsort()

array([[0, 1, 2],
       [0, 1, 2]])

# 2D Array Indexing

In [17]:
#Slicing
b.sum(axis=1)

array([[13,  4, 17]])

In [31]:
b=np.array([[9,4,1],[2,0,7],[2,0,7]])
print(b)

[[9 4 1]
 [2 0 7]
 [2 0 7]]


In [36]:
b[0:3,:2]

array([[9, 4],
       [2, 0],
       [2, 0]])

In [33]:
b[0:5]

array([[9, 4, 1],
       [2, 0, 7],
       [2, 0, 7]])